/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ads.poo;

public class App {
    public static void main(String[] args) {

        Caneta c1 = new Caneta();
        c1.cor = " "+"azul";
        c1.destampar();
        c1.status(); //metodo
        c1.Ponta = 0.5f; //atributo
        c1.rabiscar();

        // C1. é a substituição do objeto que chamou, uma referencia




    }
}
